### ISSUE TITLE
provide feature to disable cli(clap) for libs

### ISSUE THREAD

**Issue by kolbma** [svenstaro/fints-institute-db#170]
Hello,

can you please provide a feature to disable the cli dependencies for using your lib without pulling in the clap dependency!

serde has a derive feature (no need for serde_derive crate) and serde_json is also cli.

More or less this should be all to do...

```toml
# Cargo.toml
[dependencies]
clap = { version = "4", features = ["derive", "cargo", "wrap_help", "deprecated"], optional = true }
clap_complete = { version = "4", optional = true }
clap_mangen = { version = "0.2", optional = true }
iban_validate = "4"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }

[features]
default = ["cli"]
cli = ["clap", "clap_complete", "clap_mangen", "serde_json"]
```

```rust
// src/bin/cli.rs
#![cfg(feature = "cli")]

use std::{error::Error, io};

[...]
```

```rust
// tests/cli.rs
#![cfg(feature = "cli")]

use std::process::Command;

[...]
```
Thx
